### ISSUE TITLE
1.12.2 crash with Future MC

### ISSUE THREAD

**Issue by lartts** [coolsimulations/SurvivalPlus-Lightsabers#10]
Crash Report:

---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-04-14 22:04:08 ICT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SurvivalPlus Lightsabers (lightsaber)
Caused by: java.lang.NoSuchMethodError: thedarkcolour.futuremc.recipe.smithing.SmithingRecipe.<init>(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
    at net.coolsimulations.SurvivalPlus.core.util.SurvivalPlusFutureRecipes.addSmithingRecipe(SurvivalPlusFutureRecipes.java:86)
    at net.coolsimulations.SurvivalPlus.core.util.SurvivalPlusFutureRecipes.addOreDictionarySmithingRecipe(SurvivalPlusFutureRecipes.java:253)
    at net.coolsimulations.SurvivalPlus.core.util.SurvivalPlusFutureRecipes.addOreDictionarySmithingRecipe(SurvivalPlusFutureRecipes.java:243)
    at net.coolsimulations.Lightsaber.init.LightsaberFutureMCRecipes.init(LightsaberFutureMCRecipes.java:12)
    at net.coolsimulations.Lightsaber.Lightsaber.init(Lightsaber.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 747311984 bytes (712 MB) / 2329935872 bytes (2222 MB) up to 11453595648 bytes (10923 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 81 mods loaded, 81 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                        | Version                  | Source                                            | Signature                                |
       |:----- |:------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                 | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHI  | mcp                       | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHI  | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                     | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | creativecoredummy         | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCHI  | itemphysic                | 1.4.0                    | minecraft.jar                                     | None                                     |
       | LCHI  | foamfixcore               | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCHI  | swordskillsapi            | 1.1.0                    | 1.12.2-SwordSkillsApi-1.1.0.jar                   | None                                     |
       | LCHI  | dynamicswordskills        | 1.12.2-6.0.1             | 1.12.2-DynamicSwordSkills-6.0.1.jar               | None                                     |
       | LCHI  | aiimprovements            | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                   | None                                     |
       | LCHI  | aireducer                 | 0.3.0                    | AIReducer-1.12.2-0.3.0.jar                        | None                                     |
       | LCHI  | aquaacrobatics            | 1.13.0                   | AquaAcrobatics-1.13.0.jar                         | None                                     |
       | LCHI  | asmc                      | 1.0.2                    | ASMC-1.12.2-1.0.2.jar                             | None                                     |
       | LCHI  | backportedblocks          | 1.2                      | backportedblocks-1.2.jar                          | None                                     |
       | LCHI  | badmobs                   | 1.1.40                   | BadMobs-1.12.2-1.1.40.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | betterhurttimer           | 1.12.2-1.3.0.0           | BetterHurtTimer-1.12.2-1.5.0.1.jar                | 72cd337644e68ff7257f69b2927894048793e577 |
       | LCHI  | betterthirdperson         | 1.5.4                    | BetterThirdPerson-Forge-1.12.2-1.5.4.jar          | None                                     |
       | LCHI  | collisiondamage           | 1.2.1                    | CollisionDamage-1.2.1.jar                         | None                                     |
       | LCHI  | combatrefined             | 1.4.1                    | combatrefined-1.4.1.jar                           | None                                     |
       | LCHI  | controlling               | 3.0.10                   | Controlling-3.0.10.jar                            | None                                     |
       | LCHI  | extendedrenderer          | v1.0                     | coroutil-1.12.1-1.2.37.jar                        | None                                     |
       | LCHI  | coroutil                  | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                        | None                                     |
       | LCHI  | configmod                 | v1.0                     | coroutil-1.12.1-1.2.37.jar                        | None                                     |
       | LCHI  | creativecore              | 1.10.0                   | CreativeCore_v1.10.70_mc1.12.2.jar                | None                                     |
       | LCHI  | damagetilt                | 0.1.0                    | DamageTilt-1.12.2-0.1.0.jar                       | None                                     |
       | LCHI  | orelib                    | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | dsurround                 | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | elenaidodge2              | 1.1.0                    | ElenaiDodge2-1.12.2-1.1.0.jar                     | None                                     |
       | LCHI  | enderskills               | 1.12.2-1.14.0.3          | EnderSkills-1.12.2-1.14.0.3.jar                   | None                                     |
       | LCHI  | enhancedvisuals           | 1.3.0                    | EnhancedVisuals_v1.4.4_mc1.12.2.jar               | None                                     |
       | LCHI  | entityculling             | 5.2.3                    | EntityCulling-1.12.2-5.2.3.jar                    | None                                     |
       | LCHI  | fbp                       | 2.4.1                    | FancyBlockParticles-1.12.x-2.4.1.jar              | None                                     |
       | LCHI  | farseek                   | 2.5.1                    | Farseek-1.12-2.5.1.jar                            | None                                     |
       | LCHI  | fastgamemodeswitch        | 1.0.0                    | Fast Gamemode Switch 1.12.2 - 1.2.jar             | None                                     |
       | LCHI  | foamfix                   | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                        | None                                     |
       | LCHI  | forgelin                  | 1.8.4                    | Forgelin-1.8.4.jar                                | None                                     |
       | LCHI  | freelook                  | 1.2.2                    | FreeLook-1.2.2.jar                                | None                                     |
       | LCHI  | futuremc                  | 0.2.6                    | future-mc-0.2.9.jar                               | None                                     |
       | LCHI  | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCHI  | iblis_headshots           | 1.2.6                    | iblis-headshots-1.2.6.jar                         | None                                     |
       | LCHI  | ichunutil                 | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHI  | bettercombatmod           | 1.5.6                    | ImmersiveCombat(BetterCombatRebirth)-3-6-2022.jar | None                                     |
       | LCHI  | inventoryspam             | 1.0.5                    | InventorySpam-1.12.2-1.0.5.jar                    | None                                     |
       | LCHI  | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHI  | invmove                   | 0.4.6                    | InvMove-1.12.2-0.4.6.jar                          | None                                     |
       | LCHI  | jei                       | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                         | None                                     |
       | LCHI  | itemzoom                  | 1.11                     | itemzoom_1.12.2-1.11.jar                          | None                                     |
       | LCHI  | jeid                      | 1.0.4-SNAPSHOT           | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar             | None                                     |
       | LCHI  | mobamputation             | 7.0.0                    | MobAmputation-1.12.2-7.0.1.jar                    | None                                     |
       | LCHI  | mobends                   | 1.2.1                    | MoBends_1.12.2-1.2.1-19.12.21.jar                 | None                                     |
       | LCHI  | modularmovements          | ${version}               | modularmovements-1.0.1f.jar                       | None                                     |
       | LCHI  | mousetweaks               | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCHI  | moveplus                  | 1.12.1-2.4.6             | moveplus-1.12.1-2.4.6.jar                         | None                                     |
       | LCHI  | llibrary                  | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | mowziesmobs               | 1.5.8                    | mowziesmobs-1.5.8.jar                             | None                                     |
       | LCHI  | neat                      | 1.4-17                   | Neat 1.4-17.jar                                   | None                                     |
       | LCHI  | parcool                   | ${version}               | ParCool-1.12.2-1.0.0.0-α.jar                      | None                                     |
       | LCHI  | parry                     | 1.0                      | parry-1.0-hotfix.jar                              | None                                     |
       | LCHI  | particleculling           | v1.3                     | particleculling-1.12.2-v1.3.1.jar                 | None                                     |
       | LCHI  | regeneration              | 3.0.3                    | Regeneration-3.0.3.jar                            | None                                     |
       | LCHI  | repose                    | 1.6.4                    | Repose-1.12-1.6.4.jar                             | None                                     |
       | LCHI  | shieldbreak               | 1.0.1                    | ShieldBreak-1.0.1.jar                             | None                                     |
       | LCHI  | shouldersurfing           | 2.2.1                    | ShoulderSurfing-1.12.2-2.2.2.jar                  | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCHI  | soundfilters              | 0.12.1_for_1.12          | SoundFilters-0.12.1_for_1.12.jar                  | None                                     |
       | LCHI  | speedbasedfalldamage      | 1.0.2                    | SpeedBasedFallDamage-1.0.2.jar                    | None                                     |
       | LCHI  | starfall_star_warsish_mod | 1.0.0                    | Starfall_1.1.jar                                  | None                                     |
       | LCHI  | starwars                  | 8.9                      | StarWars[1.12.2]-8.9.jar                          | None                                     |
       | LCHI  | survivalplus              | 0.1.6b                   | SurvivalPlus-1.12.2-0.1.6b.jar                    | None                                     |
       | LCHE  | lightsaber                | 0.1.6c                   | SurvivalPlus-Lightsabers-1.12.2-0.1.6c.jar        | None                                     |
       | LCH   | swordblockingcombat       | 1.2.3                    | SwordBlockingCombat-v1.2.3-1.12.2.jar             | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCH   | texfix                    | 4.0                      | TexFix V-1.12-4.0.jar                             | None                                     |
       | LCH   | travelersbackpack         | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35.jar               | None                                     |
       | LCH   | underwater                | 0.9.2                    | underwater-0.9.2.jar                              | None                                     |
       | LCH   | vanillafix                | 1.0.10-150               | VanillaFix-1.0.10-150.jar                         | None                                     |
       | LCH   | walljump                  | 1.3.2                    | walljump-1.12.2-1.3.2.jar                         | None                                     |
       | LCH   | wawla                     | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | whatloomsahead            | 1.2.2                    | whatloomsahead-1.12.2-1.2.2.jar                   | None                                     |
       | LCH   | wts                       | 1.1.0                    | WTS-1.1.0.jar                                     | None                                     |
       | LCH   | recipehandler             | 0.14                     | YARCF-0.14(1.12.2).jar                            | None                                     |
       | LCH   | turtdance                 | 1.0                      | zoology_of_withernauts-1.0.jar                    | None                                     |
       | LCH   | phosphor-lighting         | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar       | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      Aqua Acrobatics Transformer (AquaAcrobatics-1.13.0.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      EntityCullingPlugin (EntityCulling-1.12.2-5.2.3.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
                                      Regeneration (Regeneration-3.0.3.jar)
                                        me.suff.mc.regen.asm.RegenClassTransformer
                                      FarseekCoreMod (Farseek-1.12-2.5.1.jar)
                                        farseek.core.FarseekClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      ShoulderPlugin (ShoulderSurfing-1.12.2-2.2.2.jar)
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityPlayerRayTrace
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver2
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererOrientCamera
                                        com.teamderpy.shouldersurfing.asm.transformers.EntityRendererRayTrace
                                        com.teamderpy.shouldersurfing.asm.transformers.GuiIngameRenderAttackIndicator
                                        com.teamderpy.shouldersurfing.asm.transformers.GuiCrosshairsBCRenderAttackIndicator
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      ModularMovementsPlugin (modularmovements-1.0.1f.jar)
                                        mchhui.modularmovements.coremod.minecraft.EntityPlayerSP
                                        mchhui.modularmovements.coremod.minecraft.Entity
                                      FutureMC (future-mc-0.2.9.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.41' Renderer: 'NVIDIA GeForce GT 1030/PCIe/SSE2'
  Suspected Mods: SurvivalPlus (survivalplus), SurvivalPlus Lightsabers (lightsaber)
  Launched Version: forge-14.23.5.2859
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.41, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

**Comment by coolsimulations** [comment]
Thanks for the report! This has been fixed with this commit https://github.com/coolsimulations/SurvivalPlus/commit/c9fbe893be52f82e259784d57f9872ed7c829d96. The update will release when 1.19 drops
