### ISSUE TITLE
Roughly Enough Items Plugin stops my server [WTHIT Related?]

### ISSUE THREAD

**Issue by Chill907Gaming** [coolsimulations/SurvivalPlus-Lightsabers#11]
Starting my server up after adding SurvivalPlus Lightsabers and SurvivalPlus on 1.19:
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by SurvivalPlus Lightsabers. Please use "rei_server", "rei_client" or "rei_common" instead. 

I can send more info if need be. When starting my mods on my client side a similar message popped up and I was able to simply ignore it and play normally, however I cannot start my server with this mod installed. I hope to help you get this fixed
[rei.log](https://github.com/coolsimulations/SurvivalPlus-Lightsabers/files/8885337/rei.log)
[latest.log](https://github.com/coolsimulations/SurvivalPlus-Lightsabers/files/8885338/latest.log)
.

**Comment by coolsimulations** [comment]
Nah, shouldn't be WTHIT related. It looks like REI changed some stuff in 1.19 that I need to adapt to. Will release a fix within the next few days. In the meanwhile, you can remove REI from your server and still use it on the client without much difference.

**Comment by coolsimulations** [comment]
Fix and released with https://github.com/coolsimulations/SurvivalPlus-Lightsabers/commit/35ce816cb9fe5185f509f4d784d591023fe4b5a4
