### ISSUE TITLE
Compatibility with Universal Enchants

### ISSUE THREAD

**Issue by 48004800** [coolsimulations/SurvivalPlus-Lightsabers#13]
https://www.curseforge.com/minecraft/mc-mods/universal-enchants-forge/files/3962009

https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers/files/3871594
Mod version information

All lightsabers cannot be enchanted

**Comment by coolsimulations** [comment]
Tested and works when setting the option `allow_mod_item_support` in the config to `true`. The config can be found in the world save under `serverconfig` and is called `universalenchants-server.toml`.
