### ISSUE TITLE
The lightsaber is identified as a shield

### ISSUE THREAD

**Issue by 48004800** [coolsimulations/SurvivalPlus-Lightsabers#14]
This is a problem between mods, not the lightsaber mod itself

Related mod link
https://www.curseforge.com/minecraft/mc-mods/apotheosis

I use the reforge table to give the lightsaber a better rarity
After several attempts, I found that the lightsaber was recognized as a shield, and the buff effect of the lightsaber was the same as that of the shield.

This results in the lightsaber-related effect bonus to be used in the auxiliary hand

However, better combat does not allow this. The lightsaber mod is compatible with better combat and lightsaber is a two-handed weapon.

**Comment by 48004800** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/78255094/214535425-bb4eeaf0-3819-4efc-9fe9-fdcb9e64917a.png">

**Comment by 48004800** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/78255094/214535623-3619d194-30a9-41af-8062-91e902d7b83c.png">
In contrast, this is a sword

**Comment by coolsimulations** [comment]
That’s because the Lightsaber can used as a shield. In the code it has the method isShield marked as true in order to work. Apotheosis must be checking for shields before swords and apply that instead. Better combat is unrelated. Nothing I can fix on my end.
