### ISSUE TITLE
Is it possible to try adding "smithing table" to version 1.12.2?

### ISSUE THREAD

**Issue by GalaxyZEROX** [coolsimulations/SurvivalPlus-Lightsabers#2]
The main reason is that the lightsaber is not assembled by oneself, and there is no ritual feeling. . . . And sometimes Obi-Wan and Moore are killed without noticing. . . . .

**Comment by coolsimulations** [comment]
Simply, no. I’m not going to have two different ways of crafting in the same version. What I will do though, is add support for [Future Versions](https://www.curseforge.com/minecraft/mc-mods/future-minecraft ) that does add in the real smithing table and I’ll use that.

**Comment by coolsimulations** [comment]
Correction, I meant support for [FutureMC](https://www.curseforge.com/minecraft/mc-mods/future-mc), since Future Versions is an MCreator mod I will not support it...
