### ISSUE TITLE
[suggestion] sound

### ISSUE THREAD

**Issue by GalaxyZEROX** [coolsimulations/SurvivalPlus-Lightsabers#6]
I have designed a new protective animation. Is there any way to make the sound of waving lightsaber continuously when blocking with the right button?

https://user-images.githubusercontent.com/73332842/129473899-c758db75-d554-40e7-aafc-60835a19eb88.mp4

**Comment by coolsimulations** [comment]
No, unfortunately, I cannot have any continuous sounds, it doesn't matter if it's idle or blocking. Thanks anyway.
