### ISSUE TITLE
[1.18.1] Crash when hovering Lightsaber in inventory with LevelZ installed.

### ISSUE THREAD

**Issue by lizfinite** [coolsimulations/SurvivalPlus-Lightsabers#7]
As I said in [Issue #81](https://github.com/Globox1997/LevelZ/issues/81) over on LevelZ repo, not sure where this issue should go so I'm (re)creating it here. 

Crash Log: [https://paste.ee/p/Klhil](https://paste.ee/p/Klhil)

**Mods:**
- fabric-api-0.45.0+1.18
- cloth-config-6.1.48-fabric
- levelz-1.1.4
- modmenu-3.0.1
- SurvivalPlus-Fabric-1.18.1-0.1.6
- SurvivalPlus-Lightsabers-Fabric-1.18.1-0.1.6

**Steps to reproduce:**
1. Enter world
2. Give any lightsaber
3. Hover within inventory

**Comment by coolsimulations** [comment]
This is an issue with LevelZ, not with Lightsabers. I will leave this issue open until it is resolved but I will contribute to the linked issue.

**Comment by coolsimulations** [comment]
Just saw that this was fixed on LevelZ's end. Closing.
