### ISSUE TITLE
[Feature Request] Adding to AQM

### ISSUE THREAD

**Issue by itsdinkd** [coolsimulations/SurvivalPlus-Lightsabers#8]
Hello, Love this mod. I am the developer of https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2 

I love what I am seeing with this and would love to feature it in my modpack. However, the only issue is the damage values. They are too high to fit my pack and would easily be the highest damaging weapon. i could make it very difficult to craft, but I;'d like to work this into progression allowing early game access into one of the sabers. 

Would you be able to create config options to modify the damage/attack speed/projectile reflect chance per saber?

**Comment by coolsimulations** [comment]
Yeah, I can look at adding that. Could be out within a week or so.

**Comment by itsdinkd** [comment]
awesome, thank you

**Comment by itsdinkd** [comment]
any update on this

**Comment by coolsimulations** [comment]
Working on it. I have 5 mods I’m working on right now and trying to time it so that the new SurvivalPlus/MoreThanAPickaxe comes out at the same time as this Lightsaber. Should be no later than the end of this next week.

**Comment by coolsimulations** [comment]
Done and Released.
