### ISSUE TITLE
Players do not drop their loot when they die from a lightsaber attack

### ISSUE THREAD

**Issue by LeModeur39** [coolsimulations/SurvivalPlus-Lightsabers#9]
When I kill a player with a lightsaber, even with a grave mod the loot does not drop. Also does this on mobs.

**Comment by coolsimulations** [comment]
What minecraft version are you on? What mod loader (Forge or Fabric)? What exact Grace mod is it? What do you mean by mobs, does killing a cow for example drop nothing?

**Comment by LeModeur39** [comment]
Nevermind I realised I used an outdated version of the mod, it works fine now.
